import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ur')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return localizations ?? AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'PakFasal',
      'welcome': 'Welcome to PakFasal',
      'login': 'Login',
      'signup': 'Sign Up',
      'or': 'OR',
      'email': 'Email',
      'username': 'Username',
      'usernameHint': 'John Doe',
      'emailHint': 'you@example.com',
      'password': 'Password',
      'passwordHint': '••••••••',
      'phone': 'Phone (Optional)',
      'phoneHint': '+92 300 0000000',
      'forgotPassword': 'Forgot Password?',
      'rememberMe': 'Remember Me',
      'requireBiometricAutofill': 'Require biometric unlock for autofill',
      'rememberMeHint':
          'Credentials are encrypted on this device. Biometric unlock may be required.',
      'resetPassword': 'Reset Password',
      'resetPasswordHint':
          'Enter your email address and we will send you a password reset link.',
      'sending': 'Sending...',
      'backToLogin': 'Back to Login',
      'home': 'Home',
      'learning': 'Learning',
      'learningDashboardHint': 'Pick a topic to start learning',
      'learningHubEyebrow': 'PakFasal · Learning Hub',
      'learningTopicsLabel': 'TOPICS',
      'learningHeadlineQuestion': 'What would you like\nto learn?',
      'learningTipBoldPrefix': 'New topics weekly. ',
      'learningTipRest':
          'Content is curated for Pakistani farmers — in Urdu and English.',
      'learningStatusAvailable': 'Available',
      'learningOptionYoutubeDesc': 'Expert tutorials by crop',
      'learningOptionArticlesDesc': 'Guides, tips & research',
      'learningOptionPestsDesc': 'Identify & treat problems',
      'learningOptionCropStagesDesc': 'Growth & harvest timelines',
      'learningYoutubeVideos': 'YouTube Learning Videos',
      'learningOptionYoutube': 'YouTube Learning Videos',
      'learningOptionArticles': 'Learning Articles',
      'learningOptionPests': 'Keera (Pests) aur Bimariyaan',
      'learningOptionCropStages': 'Fasal Ki Kasht Ke Marahil',
      'comingSoon': 'Coming soon',
      'cropDiseasePickCrop': 'Choose a crop',
      'cropDiseasePickCropHint':
          'Tap a crop to see common diseases, symptoms, and treatment tips.',
      'cropDiseaseMoreCropsSoon': 'More crops coming soon.',
      'cropDiseaseDetailSubtitle': 'Common diseases & treatment tips',
      'cropDiseaseSymptoms': 'Symptoms',
      'cropDiseaseSolution': 'Treatment',
      'cropDiseaseTopicsShort': 'topics',
      'cdCottonLcvName': 'Leaf Curl Virus',
      'cdCottonLcvDesc':
          'A viral disease spread by whiteflies that stunts growth and distorts leaves.',
      'cdCottonLcvSym1': 'Leaves curl upward or downward',
      'cdCottonLcvSym2': 'Plant growth is stunted',
      'cdCottonLcvSol1': 'Use resistant seed varieties',
      'cdCottonLcvSol2': 'Control whitefly populations',
      'cdCottonBollName': 'Boll Rot',
      'cdCottonBollDesc':
          'Fungal decay of cotton bolls, common in warm humid conditions.',
      'cdCottonBollSym1': 'Bolls soften and rot',
      'cdCottonBollSym2': 'Discoloration on bolls',
      'cdCottonBollSol1': 'Maintain proper irrigation — avoid waterlogging',
      'cdCottonBollSol2': 'Apply recommended fungicide sprays',
      'cdCottonWfName': 'Whitefly Attack',
      'cdCottonWfDesc':
          'Sap-sucking pests that weaken plants and spread viral diseases.',
      'cdCottonWfSym1': 'Yellowing leaves',
      'cdCottonWfSym2': 'Sticky honeydew on leaves',
      'cdCottonWfSol1': 'Use approved insecticides as directed',
      'cdCottonWfSol2': 'Neem-based sprays as a supplementary measure',
      'cdWheatRustName': 'Rust Disease',
      'cdWheatRustDesc':
          'Fungal infection producing rusty pustules on leaves and stems.',
      'cdWheatRustSym1': 'Orange or brown spots on leaves',
      'cdWheatRustSol1': 'Plant rust-resistant varieties',
      'cdWheatRustSol2': 'Apply fungicides when advised',
      'cdWheatSmutName': 'Smut Disease',
      'cdWheatSmutDesc':
          'Fungal disease that replaces grains with black spore masses.',
      'cdWheatSmutSym1': 'Black powder inside affected grains',
      'cdWheatSmutSol1': 'Treat seed before sowing',
      'cdWheatAphidName': 'Aphid Attack',
      'cdWheatAphidDesc':
          'Small insects that suck sap and can transmit viruses.',
      'cdWheatAphidSym1': 'Weak, stunted plants',
      'cdWheatAphidSym2': 'Curled or distorted leaves',
      'cdWheatAphidSol1':
          'Apply insecticide spray when thresholds are reached',
      'cdRiceBlbName': 'Bacterial Leaf Blight',
      'cdRiceBlbDesc':
          'Bacterial infection that spreads quickly in warm humid weather.',
      'cdRiceBlbSym1': 'Yellowing and drying of leaf edges',
      'cdRiceBlbSol1': 'Improve field drainage',
      'cdRiceBlbSol2': 'Use resistant seed varieties',
      'cdRiceBlastName': 'Blast Disease',
      'cdRiceBlastDesc':
          'Major fungal disease affecting leaves, nodes, and panicles.',
      'cdRiceBlastSym1': 'Diamond-shaped spots on leaves',
      'cdRiceBlastSol1': 'Timely fungicide application',
      'cdRiceBlastSol2': 'Balanced fertilizer use',
      'cdRiceBorerName': 'Stem Borer',
      'cdRiceBorerDesc':
          'Larvae tunnel inside stems and disrupt water and nutrient flow.',
      'cdRiceBorerSym1': 'Dead heart in young plants',
      'cdRiceBorerSol1':
          'Pheromone traps for monitoring and mass trapping',
      'cdRiceBorerSol2': 'Insecticides when economically justified',
      'weather': 'Weather',
      'askAi': 'Ask AI',
      'sensorData': 'Sensor Data',
      'marketplace': 'Marketplace',
      'cropCalendar': 'Crop Calendar',
      'offline': 'Offline',
      'online': 'Online',
      'cached': 'Cached',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'chat': 'Chat',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'saveChanges': 'Save Changes',
      'saving': 'Saving...',
      'profileUpdated': 'Profile updated successfully.',
      'voice': 'Voice',
      'notifications': 'Notifications',
      'quickAccess': 'Quick Access',
      'goodMorning': 'Good Morning!',
      'goodAfternoon': 'Good Afternoon!',
      'goodEvening': 'Good Evening!',
      'appTagline': 'Smart Farming, Better Tomorrow',
      'notificationIrrigationReminder':
          'Irrigation reminder: Check soil moisture today.',
      'notificationWeatherAlert':
          'Weather alert: Possible rain in next 24 hours.',
      'notificationMarketplaceOffer':
          'Marketplace: New fertilizer offer available.',
      'feelsLike': 'Feels like',
      'updatedJustNow': 'Updated just now',
      'wind': 'Wind',
      'latest': 'Latest',
      'dayShort': 'D',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'rainChance': 'Rain Chance',
      'weatherClear': 'Clear',
      'weatherCloudy': 'Cloudy',
      'weatherRain': 'Rain',
      'weatherSnow': 'Snow',
      'weatherStorm': 'Storm',
      'weatherGeneral': 'Weather',

      // ── Weather screen redesign ──
      'weatherToday': 'Today',
      'weatherTomorrow': 'Tomorrow',
      'weatherNow': 'Now',
      'weatherHourlyTitle': 'Hourly forecast',
      'weather7DayTitle': '7-day forecast',
      'weatherHighlights': 'Today\u2019s highlights',
      'weatherSunrise': 'Sunrise',
      'weatherSunset': 'Sunset',
      'weatherUVIndex': 'UV Index',
      'weatherUVLow': 'Low',
      'weatherUVModerate': 'Moderate',
      'weatherUVHigh': 'High',
      'weatherUVVeryHigh': 'Very high',
      'weatherUVExtreme': 'Extreme',
      'weatherAirQuality': 'Air quality',
      'weatherPressure': 'Pressure',
      'weatherVisibility': 'Visibility',
      'weatherDewPoint': 'Dew point',
      'weatherCloudCover': 'Cloud cover',
      'weatherHigh': 'H',
      'weatherLow': 'L',
      'weatherMinMax': 'Min/Max',
      'weatherRefresh': 'Refresh',
      'weatherSearchCity': 'Search city',
      'weatherSearchCityHint': 'Type a city name (e.g. Lahore)',
      'weatherUseCurrentLocation': 'Use current location',
      'weatherSavedLocations': 'Saved locations',
      'weatherRemove': 'Remove',
      'weatherNoSearchResults': 'No matching cities found.',
      'dowMon': 'Mon',
      'dowTue': 'Tue',
      'dowWed': 'Wed',
      'dowThu': 'Thu',
      'dowFri': 'Fri',
      'dowSat': 'Sat',
      'dowSun': 'Sun',
      'weatherSearchError': 'Could not search cities. Try again.',
      'weatherLocationDenied': 'Location permission is required.',
      'weatherLocationDisabled': 'Please turn on device location services.',
      'weatherOpenSettings': 'Open settings',
      'weatherOfflineNotice':
          'You\u2019re offline. Showing last saved weather.',
      'weatherFetchError':
          'Could not load latest weather. Pull down to retry.',
      'weatherNoApiKeyNotice':
          'OPENWEATHER_API_KEY not set. Using free fallback provider.',
      'weatherCancel': 'Cancel',

      // ── Crop alerts ──
      'cropAlertHeavyRain': 'Heavy rain alert',
      'cropAlertHeavyRainBody':
          'Heavy rainfall expected. Postpone irrigation and secure produce.',
      'cropAlertHeatwave': 'Heatwave alert',
      'cropAlertHeatwaveBody':
          'Extreme heat expected. Irrigate early morning and protect young crops.',
      'cropAlertHighWind': 'High wind alert',
      'cropAlertHighWindBody':
          'Strong winds expected. Avoid spraying and secure field covers.',
      'cropAlertFrost': 'Frost warning',
      'cropAlertFrostBody':
          'Frost likely tonight. Protect sensitive crops and seedlings.',
      'cropAlertThunderstorm': 'Thunderstorm warning',
      'cropAlertThunderstormBody':
          'Thunderstorms expected. Stay away from open fields and tall trees.',

      // ── Farmer advisories ──
      'farmerAdvisory': 'Farmer advisory',
      'advisoryGoodIrrigation': 'Good day for irrigation',
      'advisoryGoodIrrigationBody':
          'Mild temperature with low rain chance. Ideal window to water your fields.',
      'advisoryAvoidIrrigation': 'Skip irrigation today',
      'advisoryAvoidIrrigationBody':
          'Rain expected within 24 hours \u2014 save water and let nature do the work.',
      'advisoryAvoidSpraying': 'Avoid pesticide spray today',
      'advisoryAvoidSprayingBody':
          'High wind or rain reduces spray efficiency and may harm nearby crops.',
      'advisoryGoodSpraying': 'Good window for spraying',
      'advisoryGoodSprayingBody':
          'Calm winds and dry weather \u2014 a safe time to apply pesticides early morning.',
      'advisoryRainTomorrow': 'Rain expected tomorrow',
      'advisoryRainTomorrowBody':
          'Plan field operations today; harvest mature produce if possible.',
      'advisoryHarvestWindow': 'Good harvest window',
      'advisoryHarvestWindowBody':
          'Dry, mild weather expected next 48 hours. Plan harvesting accordingly.',
      'advisoryProtectFromHeat': 'Protect crops from heat',
      'advisoryProtectFromHeatBody':
          'Use mulching and irrigate early morning to reduce heat stress.',

      // ── Misc weather UI ──
      'mph': 'mph',
      'kmh': 'km/h',
      'percent': '%',
      'degreeC': '°C',
      'hpa': 'hPa',
      'km': 'km',
      'soilMoisture': 'Soil Moisture',
      'phLevel': 'pH Level',
      'contact': 'Contact',
      'send': 'Send',
      'typeMessage': 'Type your question...',
      'listening': 'Listening...',
      'voiceInputUnavailable':
          'Voice input is unavailable. Please allow microphone permission.',
      'voicePermissionDenied':
          'Microphone permission is denied. Enable it from app settings.',
      'voiceServiceUnavailable':
          'Speech service is unavailable on this device. Please install/update Google Speech services.',
      'voiceInputStartFailed':
          'Could not start voice input. Please try again.',
      'voiceTapToSpeak': 'Tap mic to speak',
      'voiceListeningNow': 'Listening... speak now',
      'voiceProcessing': 'Processing voice input...',
      'openSettings': 'Open Settings',
      'good': 'Good',
      'moderate': 'Moderate',
      'bad': 'Bad',
      'errorState': 'Something went wrong.',
      'retry': 'Retry',
      'loading': 'Loading...',
      'learningSubtitle': 'Trusted farming videos by crop category',
      'featuredLearning': 'Featured Lesson',
      'watchNow': 'Watch Now',
      'learningEmpty': 'No videos found for this category yet.',
      'learningFilterByCrop': 'Filter by crop',
      'learningSearchHint': 'Search videos by title or channel...',
      'learningNoSearchResults': 'No videos match your search.',
      'learningDemoMode':
          'Demo videos are shown. Add YOUTUBE_API_KEY using --dart-define to load live YouTube data.',
      'marketSearchHint': 'Search product name',
      'marketFilterCompany': 'Filter by company',
      'marketOfflineCached': 'Showing cached products while offline.',
      'marketNoProducts': 'No products match your search or filters.',
      'marketCompany': 'Company',
      'marketCategory': 'Category',
      'marketDetail': 'Product Detail',
      'marketLocation': 'Location',
      'callCompany': 'Call Company',
      'whatsapp': 'WhatsApp',
      'verified': 'Verified',
      'soilMoistureTrend': 'Soil Moisture Trend (7 days)',
      'phTrend': 'pH Trend (7 days)',
      'dssRecommendation': 'Smart Recommendation',
      'sensorRecommendationText':
          'Soil moisture is healthy. Keep next irrigation after 24-36 hours and apply balanced fertilizer this week.',
      'lastUpdated': 'Last updated',
      'sensorCloudLive': 'Live cloud sensor stream connected.',
      'sensorCloudError': 'Cloud unavailable. Showing cached/demo sensor data.',
      'sensorManualInputTitle': 'Manual Sensor Input',
      'sensorCropLabel': 'Crop',
      'sensorMoistureInput': 'Soil Moisture (%)',
      'sensorPhInput': 'Soil pH',
      'sensorRainExpected': 'Rain expected in next 24 hours',
      'sensorGenerateDss': 'Generate DSS Recommendation',
      'sensorSaveSession': 'Save Session',
      'sensorExportReadings': 'Export Readings',
      'sensorSessionSaved': 'Sensor session saved.',
      'sensorCopiedClipboard': 'Readings copied as CSV to clipboard.',
      'sensorRecIrrigateSoon': 'Irrigation needed within 12-24 hours',
      'sensorRecWaitRain':
          'Moisture is low but rain is expected, wait and recheck',
      'sensorRecReduceIrrigation':
          'Reduce irrigation frequency to avoid water logging',
      'sensorRecMoistureOk': 'Moisture is in acceptable range',
      'sensorRecAcidic': 'Soil is acidic, add lime and balanced fertilizer',
      'sensorRecAlkaline': 'Soil is alkaline, apply gypsum and organic matter',
      'sensorRecPhSuitable': 'pH is suitable for',
      'splashTagline': 'Smart farming for Pakistan',
      'authSubtitle': 'Sign in to continue',
      'continueAsGuest': 'Continue as Guest',
      'authSignOut': 'Sign out',
      'authLoggingIn': 'Signing in...',
      'authCreatingAccount': 'Creating account...',
      'emailRequired': 'Email is required',
      'usernameRequired': 'Username is required',
      'usernameMinLength': 'Username must be at least 3 characters',
      'passwordMin': 'Minimum 6 characters required',
      'weakPasswordForm': 'Password must be at least 6 characters',
      'invalidEmail': 'Enter a valid email address',
      'userDisabled': 'This account has been disabled.',
      'userNotFound': 'No account found for this email.',
      'wrongPassword': 'Incorrect password. Try again.',
      'emailInUse': 'This email is already registered.',
      'weakPasswordAuth': 'Password is too weak.',
      'tooManyRequests': 'Too many attempts. Try again later.',
      'networkFailed': 'Network error. Check your connection.',
      'authUnknown': 'Authentication failed. Please try again.',
      'resetEmailSent': 'Password reset link sent to your email.',
      'confirmPassword': 'Confirm password',
      'confirmPasswordRequired': 'Please confirm your password',
      'passwordsMismatch': 'Passwords do not match.',
      'invalidPhone': 'Enter a valid phone number',
      'selectCrop': 'Select Crop',
      'cropWheat': 'Wheat',
      'cropRice': 'Rice',
      'cropCotton': 'Cotton',
      'cropSugarcane': 'Sugarcane',
      'cropMaize': 'Maize',
      'couldNotOpenVideo': 'Could not open video link',
      'couldNotOpenDialer': 'Could not open dialer',
      'couldNotOpenWhatsapp': 'Could not open WhatsApp',
      'aiSampleQuestion': 'How to save wheat from pests?',
      'aiSampleAnswer':
          'Use approved pesticide early morning and monitor weekly.',
      'aiPendingResponse':
          'Thanks! AI response will be connected in backend integration.',
      'aiHistory': 'History',
      'aiNewChat': 'New chat',
      'aiNoMessagesTitle': 'Start your first AI chat',
      'aiNoMessagesSubtitle':
          'Ask about crops, pests, weather, or fertilizer recommendations.',
      'aiAssistantLabel': 'PakFasal AI',
      'aiYouLabel': 'You',
      'aiHistoryLoaded': 'Chat history loaded',
      'aiTyping': 'AI is typing...',
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'onboardingTitle1': 'Weather-smart crop planning',
      'onboardingDesc1':
          'Get daily weather updates and farm-friendly insights before every field decision.',
      'onboardingTitle2': 'Learn better farming practices',
      'onboardingDesc2':
          'Watch trusted lessons by crop type and improve yield with practical guidance.',
      'onboardingTitle3': 'Track your farm with confidence',
      'onboardingDesc3':
          'Use sensor trends and recommendations to plan irrigation and soil care on time.',
    },
    'ur': {
      'appName': 'پاک فصل',
      'welcome': 'پاک فصل میں خوش آمدید',
      'login': 'لاگ اِن',
      'signup': 'رجسٹر کریں',
      'or': 'یا',
      'email': 'ای میل',
      'username': 'صارف نام',
      'usernameHint': 'مثال: علی خان',
      'emailHint': 'you@example.com',
      'password': 'پاس ورڈ',
      'passwordHint': '••••••••',
      'phone': 'فون (اختیاری)',
      'phoneHint': '+92 300 0000000',
      'forgotPassword': 'پاس ورڈ بھول گئے؟',
      'rememberMe': 'مجھے یاد رکھیں',
      'requireBiometricAutofill': 'آٹو فل کے لیے بایومیٹرک تصدیق لازمی کریں',
      'rememberMeHint':
          'لاگ اِن معلومات اس ڈیوائس پر خفیہ انداز میں محفوظ ہوتی ہیں اور بایومیٹرک تصدیق درکار ہو سکتی ہے۔',
      'resetPassword': 'پاس ورڈ ری سیٹ کریں',
      'resetPasswordHint':
          'اپنا ای میل درج کریں، ہم آپ کو پاس ورڈ ری سیٹ لنک بھیجیں گے۔',
      'sending': 'بھیجا جا رہا ہے...',
      'backToLogin': 'لاگ اِن پر واپس جائیں',
      'home': 'ہوم',
      'learning': 'سیکھیں',
      'learningDashboardHint': 'سیکھنے کے لیے موضوع منتخب کریں',
      'learningHubEyebrow': 'پاک فصل · سیکھنے کا مرکز',
      'learningTopicsLabel': 'موضوعات',
      'learningHeadlineQuestion': 'آپ کیا سیکھنا\nچاہتے ہیں؟',
      'learningTipBoldPrefix': 'ہر ہفتے نئے موضوعات۔ ',
      'learningTipRest':
          'مواد پاکستانی کاشتکاروں کے لیے ترتیب دیا گیا ہے — اردو اور انگریزی میں۔',
      'learningStatusAvailable': 'دستیاب',
      'learningOptionYoutubeDesc': 'فصل کے مطابق ماہر ویڈیوز',
      'learningOptionArticlesDesc': 'رہنمائی، تجاویز اور تحقیق',
      'learningOptionPestsDesc': 'مسائل کی شناخت اور علاج',
      'learningOptionCropStagesDesc': 'بڑھوت اور کٹائی کے مراحل',
      'learningYoutubeVideos': 'یوٹیوب تعلیمی ویڈیوز',
      'learningOptionYoutube': 'یوٹیوب تعلیمی ویڈیوز',
      'learningOptionArticles': 'تعلیمی مضامین',
      'learningOptionPests': 'کیڑے اور بیماریاں',
      'learningOptionCropStages': 'فصل کی کاشت کے مراحل',
      'comingSoon': 'جلد آرہا ہے',
      'cropDiseasePickCrop': 'فصل منتخب کریں',
      'cropDiseasePickCropHint':
          'عام بیماریوں، علامات اور علاج کی تجاویز دیکھنے کے لیے فصل پر ٹیپ کریں۔',
      'cropDiseaseMoreCropsSoon': 'مزید فصلیں جلد شامل کی جائیں گی۔',
      'cropDiseaseDetailSubtitle': 'عام بیماریاں اور علاج کی تجاویز',
      'cropDiseaseSymptoms': 'علامات',
      'cropDiseaseSolution': 'علاج',
      'cropDiseaseTopicsShort': 'موضوعات',
      'cdCottonLcvName': 'لیف کرل وائرس',
      'cdCottonLcvDesc':
          'سفید مکھیوں سے پھیلنے والا وائرس جس سے پودے کی بڑھوت رک جاتی ہے اور پتے بگڑ جاتے ہیں۔',
      'cdCottonLcvSym1': 'پتے اوپر یا نیچے کی طرف مڑ جاتے ہیں',
      'cdCottonLcvSym2': 'پودے کی بڑھوت کم یا رک جاتی ہے',
      'cdCottonLcvSol1': 'مزاحم بیج استعمال کریں',
      'cdCottonLcvSol2': 'سفید مکھی پر قابو پائیں',
      'cdCottonBollName': 'ٹنکہ سڑن',
      'cdCottonBollDesc':
          'گرم نم موسم میں کپاس کے ٹنکوں پر فنگس کی سڑن۔',
      'cdCottonBollSym1': 'ٹنکے نرم ہو کر سڑ جاتے ہیں',
      'cdCottonBollSym2': 'ٹنکوں پر رنگ بدل جاتا ہے',
      'cdCottonBollSol1': 'درست آبپاشی کریں — پانی کھڑا نہ ہونے دیں',
      'cdCottonBollSol2': 'تجویز کردہ فنگس کش اسپرے کریں',
      'cdCottonWfName': 'سفید مکھی کا حملہ',
      'cdCottonWfDesc':
          'رس چوسنے والے کیڑے جو پودے کمزور کرتے اور وائرل بیماریاں پھیلاتے ہیں۔',
      'cdCottonWfSym1': 'پتے پیلے پڑ جاتے ہیں',
      'cdCottonWfSym2': 'پتوں پر چپچپا مادہ (شہد جیسا)',
      'cdCottonWfSol1': 'منظور شدہ کیڑے مار ادویات ہدایت کے مطابق',
      'cdCottonWfSol2': 'نیم کا اسپرے اضافی طور پر',
      'cdWheatRustName': 'رَسٹ (زنگ) کی بیماری',
      'cdWheatRustDesc':
          'فنگس سے پتوں اور تنے پر زنگ جیسے دھبے بنتے ہیں۔',
      'cdWheatRustSym1': 'پتوں پر نارنجی یا بھورے دھبے',
      'cdWheatRustSol1': 'رَسٹ سے مزاحم اقسام لگائیں',
      'cdWheatRustSol2': 'ماہر کے مشورے پر فنگس کش',
      'cdWheatSmutName': 'سَمَٹ (سُنڈی) کی بیماری',
      'cdWheatSmutDesc':
          'فنگس دانوں کی جگہ کالا بیجاں بنا دیتا ہے۔',
      'cdWheatSmutSym1': 'متاثرہ دانوں کے اندر کالی پاؤڈر جیسی چیز',
      'cdWheatSmutSol1': 'بوائی سے پہلے بیج کا علاج کریں',
      'cdWheatAphidName': 'ایفِڈ (چوسنے والے کیڑے)',
      'cdWheatAphidDesc':
          'چھوٹے کیڑے جو رس چوستے ہیں اور وائرل بھی پھیلا سکتے ہیں۔',
      'cdWheatAphidSym1': 'پودے کمزور، بڑھوت کم',
      'cdWheatAphidSym2': 'پتے مڑے یا بگڑے ہوئے',
      'cdWheatAphidSol1': 'نقصان کی حد پر پہنچنے پر کیڑے مار اسپرے',
      'cdRiceBlbName': 'جرثومہ سے پتوں کی جھلساہٹ',
      'cdRiceBlbDesc':
          'گرم نم موسم میں تیزی سے پھیلنے والی جرثومی بیماری۔',
      'cdRiceBlbSym1': 'پتوں کے کنارے پیلے ہو کر سوکھ جاتے ہیں',
      'cdRiceBlbSol1': 'کھیت کی نکاسی بہتر کریں',
      'cdRiceBlbSol2': 'مزاحم بیج استعمال کریں',
      'cdRiceBlastName': 'بلاسٹ فنگس',
      'cdRiceBlastDesc':
          'پتے، گانٹھیں اور بالیاں متاثر کرنے والی بڑی فنگس۔',
      'cdRiceBlastSym1': 'پتوں پر ہیرے کی شکل کے دھبے',
      'cdRiceBlastSol1': 'بروقت فنگس کش لگائیں',
      'cdRiceBlastSol2': 'متوازن کھاد کا استعمال',
      'cdRiceBorerName': 'تنے کا کیڑا',
      'cdRiceBorerDesc':
          'لاروا تنے کے اندر سراخ کر کے پانی اور غذائی اجزاء کی حرکت روک دیتا ہے۔',
      'cdRiceBorerSym1': 'نوجوان پودوں میں مُردہ دل (پودہ خشک نظر آتا ہے)',
      'cdRiceBorerSol1': 'فرومون جالے — نگرانی اور بڑے پیمانے پر پکڑ',
      'cdRiceBorerSol2': 'معاشی طور پر درست ہو تو کیڑے مار ادویات',
      'weather': 'موسم',
      'askAi': 'اے آئی سے پوچھیں',
      'sensorData': 'سینسر ڈیٹا',
      'marketplace': 'مارکیٹ پلیس',
      'cropCalendar': 'فصل کیلنڈر',
      'offline': 'آف لائن',
      'online': 'آن لائن',
      'cached': 'محفوظ',
      'lightMode': 'لائٹ موڈ',
      'darkMode': 'ڈارک موڈ',
      'language': 'زبان',
      'chat': 'چیٹ',
      'alerts': 'الرٹس',
      'profile': 'پروفائل',
      'saveChanges': 'تبدیلیاں محفوظ کریں',
      'saving': 'محفوظ کیا جا رہا ہے...',
      'profileUpdated': 'پروفائل کامیابی سے اپڈیٹ ہو گئی۔',
      'voice': 'آواز',
      'notifications': 'اطلاعات',
      'quickAccess': 'فوری رسائی',
      'goodMorning': 'صبح بخیر!',
      'goodAfternoon': 'دوپہر بخیر!',
      'goodEvening': 'شام بخیر!',
      'appTagline': 'اسمارٹ فارمنگ، بہتر کل',
      'notificationIrrigationReminder':
          'آبپاشی یاددہانی: آج مٹی کی نمی چیک کریں۔',
      'notificationWeatherAlert':
          'موسمی الرٹ: اگلے 24 گھنٹوں میں بارش کا امکان ہے۔',
      'notificationMarketplaceOffer':
          'مارکیٹ پلیس: کھاد کی نئی پیشکش دستیاب ہے۔',
      'feelsLike': 'محسوس ہوتا ہے',
      'updatedJustNow': 'ابھی اپڈیٹ ہوا',
      'wind': 'ہوا',
      'latest': 'تازہ ترین',
      'dayShort': 'دن',
      'temperature': 'درجہ حرارت',
      'humidity': 'نمی',
      'rainChance': 'بارش کا امکان',
      'weatherClear': 'صاف موسم',
      'weatherCloudy': 'ابر آلود',
      'weatherRain': 'بارش',
      'weatherSnow': 'برف',
      'weatherStorm': 'طوفانی',
      'weatherGeneral': 'موسم',

      // ── Weather screen redesign (Urdu) ──
      'weatherToday': 'آج',
      'weatherTomorrow': 'کل',
      'weatherNow': 'ابھی',
      'weatherHourlyTitle': 'گھنٹہ وار پیشن گوئی',
      'weather7DayTitle': '7 دن کی پیشن گوئی',
      'weatherHighlights': 'آج کی نمایاں جھلکیاں',
      'weatherSunrise': 'طلوع آفتاب',
      'weatherSunset': 'غروب آفتاب',
      'weatherUVIndex': 'یو وی انڈیکس',
      'weatherUVLow': 'کم',
      'weatherUVModerate': 'درمیانہ',
      'weatherUVHigh': 'زیادہ',
      'weatherUVVeryHigh': 'بہت زیادہ',
      'weatherUVExtreme': 'انتہائی',
      'weatherAirQuality': 'فضائی معیار',
      'weatherPressure': 'دباؤ',
      'weatherVisibility': 'منظر',
      'weatherDewPoint': 'شبنم نقطہ',
      'weatherCloudCover': 'بادل',
      'weatherHigh': 'زیادہ',
      'weatherLow': 'کم',
      'weatherMinMax': 'کم/زیادہ',
      'weatherRefresh': 'تازہ کریں',
      'weatherSearchCity': 'شہر تلاش کریں',
      'weatherSearchCityHint': 'شہر کا نام لکھیں (مثال: لاہور)',
      'weatherUseCurrentLocation': 'موجودہ مقام استعمال کریں',
      'weatherSavedLocations': 'محفوظ مقامات',
      'weatherRemove': 'ہٹائیں',
      'weatherNoSearchResults': 'کوئی شہر نہیں ملا۔',
      'dowMon': 'پیر',
      'dowTue': 'منگل',
      'dowWed': 'بدھ',
      'dowThu': 'جمعرات',
      'dowFri': 'جمعہ',
      'dowSat': 'ہفتہ',
      'dowSun': 'اتوار',
      'weatherSearchError': 'شہر تلاش نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
      'weatherLocationDenied': 'مقام کی اجازت درکار ہے۔',
      'weatherLocationDisabled': 'براہ کرم ڈیوائس کی لوکیشن آن کریں۔',
      'weatherOpenSettings': 'سیٹنگز کھولیں',
      'weatherOfflineNotice':
          'آپ آف لائن ہیں۔ آخری محفوظ موسم دکھایا جا رہا ہے۔',
      'weatherFetchError':
          'تازہ موسم لوڈ نہیں ہوا۔ دوبارہ کوشش کے لیے کھینچیں۔',
      'weatherNoApiKeyNotice':
          'OPENWEATHER_API_KEY سیٹ نہیں ہے۔ مفت متبادل استعمال کیا جا رہا ہے۔',
      'weatherCancel': 'منسوخ',

      // ── Crop alerts (Urdu) ──
      'cropAlertHeavyRain': 'شدید بارش الرٹ',
      'cropAlertHeavyRainBody':
          'شدید بارش متوقع ہے۔ آبپاشی روک دیں اور پیداوار محفوظ کریں۔',
      'cropAlertHeatwave': 'گرمی کی لہر الرٹ',
      'cropAlertHeatwaveBody':
          'انتہائی گرمی متوقع ہے۔ صبح سویرے آبپاشی کریں اور نوجوان فصلوں کی حفاظت کریں۔',
      'cropAlertHighWind': 'تیز ہوا الرٹ',
      'cropAlertHighWindBody':
          'تیز ہوائیں متوقع ہیں۔ اسپرے سے گریز کریں اور کھیت کے ڈھکن محفوظ کریں۔',
      'cropAlertFrost': 'پالے کی وارننگ',
      'cropAlertFrostBody':
          'آج رات پالا متوقع ہے۔ حساس فصلوں اور پنیریوں کی حفاظت کریں۔',
      'cropAlertThunderstorm': 'گرج چمک کی وارننگ',
      'cropAlertThunderstormBody':
          'گرج چمک متوقع ہے۔ کھلے کھیتوں اور بلند درختوں سے دور رہیں۔',

      // ── Farmer advisories (Urdu) ──
      'farmerAdvisory': 'کاشتکار مشورہ',
      'advisoryGoodIrrigation': 'آبپاشی کے لیے اچھا دن',
      'advisoryGoodIrrigationBody':
          'موزوں درجہ حرارت اور بارش کا کم امکان۔ کھیت کو پانی دینے کا بہترین وقت۔',
      'advisoryAvoidIrrigation': 'آج آبپاشی نہ کریں',
      'advisoryAvoidIrrigationBody':
          'اگلے 24 گھنٹوں میں بارش متوقع \u2014 پانی بچائیں اور قدرت پر چھوڑیں۔',
      'advisoryAvoidSpraying': 'آج اسپرے نہ کریں',
      'advisoryAvoidSprayingBody':
          'تیز ہوا یا بارش اسپرے کا اثر کم کرتی ہے اور قریبی فصلوں کو نقصان دے سکتی ہے۔',
      'advisoryGoodSpraying': 'اسپرے کے لیے مناسب وقت',
      'advisoryGoodSprayingBody':
          'ہلکی ہوا اور خشک موسم \u2014 صبح سویرے کیڑے مار اسپرے کا محفوظ وقت۔',
      'advisoryRainTomorrow': 'کل بارش متوقع',
      'advisoryRainTomorrowBody':
          'آج کے کھیت کے کام مکمل کریں؛ ممکن ہو تو پکی پیداوار کاٹ لیں۔',
      'advisoryHarvestWindow': 'کٹائی کا اچھا موقع',
      'advisoryHarvestWindowBody':
          'اگلے 48 گھنٹے خشک اور موزوں موسم۔ کٹائی کی منصوبہ بندی کریں۔',
      'advisoryProtectFromHeat': 'گرمی سے فصل بچائیں',
      'advisoryProtectFromHeatBody':
          'ملچنگ کریں اور صبح سویرے آبپاشی سے گرمی کا دباؤ کم کریں۔',

      // ── Misc weather UI (Urdu) ──
      'mph': 'میل/گھنٹہ',
      'kmh': 'کلومیٹر/گھنٹہ',
      'percent': '٪',
      'degreeC': '°C',
      'hpa': 'ہیکٹو پاسکل',
      'km': 'کلومیٹر',
      'soilMoisture': 'مٹی کی نمی',
      'phLevel': 'پی ایچ لیول',
      'contact': 'رابطہ',
      'send': 'بھیجیں',
      'typeMessage': 'اپنا سوال لکھیں...',
      'listening': 'سن رہا ہے...',
      'voiceInputUnavailable':
          'آواز سے لکھنے کی سہولت دستیاب نہیں۔ براہ کرم مائیکروفون کی اجازت دیں۔',
      'voicePermissionDenied':
          'مائیکروفون کی اجازت نہیں دی گئی۔ براہ کرم ایپ سیٹنگز سے اجازت دیں۔',
      'voiceServiceUnavailable':
          'اس ڈیوائس پر اسپیچ سروس دستیاب نہیں۔ براہ کرم گوگل اسپیچ سروس اپڈیٹ/انسٹال کریں۔',
      'voiceInputStartFailed':
          'وائس ان پٹ شروع نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
      'voiceTapToSpeak': 'بولنے کے لیے مائیک دبائیں',
      'voiceListeningNow': 'سن رہا ہے... اب بولیں',
      'voiceProcessing': 'آواز کو متن میں بدلا جا رہا ہے...',
      'openSettings': 'سیٹنگز کھولیں',
      'good': 'اچھا',
      'moderate': 'درمیانہ',
      'bad': 'خراب',
      'errorState': 'کچھ غلط ہوگیا۔',
      'retry': 'دوبارہ کوشش',
      'loading': 'لوڈ ہو رہا ہے...',
      'learningSubtitle': 'فصل کے حساب سے قابل اعتماد زرعی ویڈیوز',
      'featuredLearning': 'نمایاں سبق',
      'watchNow': 'ابھی دیکھیں',
      'learningEmpty': 'اس کیٹیگری کے لیے ابھی ویڈیوز دستیاب نہیں۔',
      'learningFilterByCrop': 'فصل کے مطابق',
      'learningSearchHint': 'عنوان یا چینل کے ذریعے تلاش کریں...',
      'learningNoSearchResults': 'آپ کی تلاش سے کوئی ویڈیو میل نہیں کھاتی۔',
      'learningDemoMode':
          'ڈیمو ویڈیوز دکھائی جا رہی ہیں۔ لائیو یوٹیوب ڈیٹا کے لیے --dart-define کے ساتھ YOUTUBE_API_KEY شامل کریں۔',
      'marketSearchHint': 'پروڈکٹ کا نام تلاش کریں',
      'marketFilterCompany': 'کمپنی کے مطابق فلٹر',
      'marketOfflineCached':
          'آف لائن حالت میں محفوظ شدہ پروڈکٹس دکھائی جا رہی ہیں۔',
      'marketNoProducts': 'تلاش یا فلٹر کے مطابق کوئی پروڈکٹ نہیں ملی۔',
      'marketCompany': 'کمپنی',
      'marketCategory': 'قسم',
      'marketDetail': 'پروڈکٹ کی تفصیل',
      'marketLocation': 'مقام',
      'callCompany': 'کمپنی کو کال کریں',
      'whatsapp': 'واٹس ایپ',
      'verified': 'تصدیق شدہ',
      'soilMoistureTrend': 'مٹی کی نمی کا رجحان (7 دن)',
      'phTrend': 'پی ایچ رجحان (7 دن)',
      'dssRecommendation': 'سمارٹ سفارش',
      'sensorRecommendationText':
          'مٹی کی نمی مناسب ہے۔ اگلی آبپاشی 24 سے 36 گھنٹے بعد کریں اور اس ہفتے متوازن کھاد استعمال کریں۔',
      'lastUpdated': 'آخری اپ ڈیٹ',
      'sensorCloudLive': 'لائیو کلاؤڈ سینسر ڈیٹا منسلک ہے۔',
      'sensorCloudError':
          'کلاؤڈ دستیاب نہیں۔ محفوظ/ڈیمو سینسر ڈیٹا دکھایا جا رہا ہے۔',
      'sensorManualInputTitle': 'دستی سینسر ان پٹ',
      'sensorCropLabel': 'فصل',
      'sensorMoistureInput': 'مٹی کی نمی (%)',
      'sensorPhInput': 'مٹی کا پی ایچ',
      'sensorRainExpected': 'اگلے 24 گھنٹوں میں بارش متوقع ہے',
      'sensorGenerateDss': 'ڈی ایس ایس سفارش بنائیں',
      'sensorSaveSession': 'سیشن محفوظ کریں',
      'sensorExportReadings': 'ریڈنگز ایکسپورٹ کریں',
      'sensorSessionSaved': 'سینسر سیشن محفوظ ہوگیا۔',
      'sensorCopiedClipboard': 'ریڈنگز CSV فارمیٹ میں کلپ بورڈ پر کاپی ہوگئیں۔',
      'sensorRecIrrigateSoon': 'اگلے 12-24 گھنٹوں میں آبپاشی کریں',
      'sensorRecWaitRain':
          'نمی کم ہے مگر بارش متوقع ہے، انتظار کریں اور دوبارہ چیک کریں',
      'sensorRecReduceIrrigation':
          'پانی کھڑا ہونے سے بچنے کے لیے آبپاشی کی مقدار کم کریں',
      'sensorRecMoistureOk': 'نمی مناسب حد میں ہے',
      'sensorRecAcidic': 'مٹی تیزابی ہے، چونا اور متوازن کھاد استعمال کریں',
      'sensorRecAlkaline': 'مٹی الکلائن ہے، جپسم اور نامیاتی مادہ استعمال کریں',
      'sensorRecPhSuitable': 'پی ایچ موزوں ہے برائے',
      'splashTagline': 'پاکستان کے لیے ذہین کھیت باڑی',
      'authSubtitle': 'جاری رکھنے کے لیے لاگ اِن کریں',
      'continueAsGuest': 'مہمان کے طور پر جاری رکھیں',
      'authSignOut': 'لاگ آؤٹ',
      'authLoggingIn': 'لاگ اِن ہو رہا ہے...',
      'authCreatingAccount': 'اکاؤنٹ بنایا جا رہا ہے...',
      'emailRequired': 'ای میل درکار ہے',
      'usernameRequired': 'صارف نام درکار ہے',
      'usernameMinLength': 'صارف نام کم از کم 3 حروف کا ہونا چاہیے',
      'passwordMin': 'کم از کم 6 حروف درکار ہیں',
      'weakPasswordForm': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
      'invalidEmail': 'درست ای میل درج کریں',
      'userDisabled': 'یہ اکاؤنٹ غیر فعال کردیا گیا ہے۔',
      'userNotFound': 'اس ای میل پر کوئی اکاؤنٹ نہیں ملا۔',
      'wrongPassword': 'غلط پاس ورڈ۔ دوبارہ کوشش کریں۔',
      'emailInUse': 'یہ ای میل پہلے سے رجسٹرڈ ہے۔',
      'weakPasswordAuth': 'پاس ورڈ بہت کمزور ہے۔',
      'tooManyRequests': 'بہت زیادہ کوششیں۔ بعد میں کوشش کریں۔',
      'networkFailed': 'نیٹ ورک خرابی۔ کنکشن چیک کریں۔',
      'authUnknown': 'لاگ اِن ناکام۔ دوبارہ کوشش کریں۔',
      'resetEmailSent': 'پاس ورڈ ری سیٹ کا لنک آپ کی ای میل پر بھیج دیا گیا۔',
      'confirmPassword': 'پاس ورڈ دوبارہ',
      'confirmPasswordRequired': 'براہ کرم پاس ورڈ دوبارہ درج کریں',
      'passwordsMismatch': 'پاس ورڈ میل نہیں کھاتے۔',
      'invalidPhone': 'درست فون نمبر درج کریں',
      'selectCrop': 'فصل منتخب کریں',
      'cropWheat': 'گندم',
      'cropRice': 'چاول',
      'cropCotton': 'کپاس',
      'cropSugarcane': 'گنا',
      'cropMaize': 'مکئی',
      'couldNotOpenVideo': 'ویڈیو لنک نہیں کھل سکا',
      'couldNotOpenDialer': 'ڈائلر نہیں کھل سکا',
      'couldNotOpenWhatsapp': 'واٹس ایپ نہیں کھل سکا',
      'aiSampleQuestion': 'گندم کو کیڑوں سے کیسے بچاؤں؟',
      'aiSampleAnswer':
          'منظور شدہ اسپرے صبح سویرے کریں اور ہفتہ وار نگرانی کریں۔',
      'aiPendingResponse':
          'شکریہ! اے آئی جواب بیک اینڈ انٹیگریشن کے بعد دستیاب ہوگا۔',
      'aiHistory': 'ہسٹری',
      'aiNewChat': 'نئی چیٹ',
      'aiNoMessagesTitle': 'اپنی پہلی اے آئی چیٹ شروع کریں',
      'aiNoMessagesSubtitle':
          'فصل، کیڑے، موسم یا کھاد کے بارے میں سوال پوچھیں۔',
      'aiAssistantLabel': 'پاک فصل اے آئی',
      'aiYouLabel': 'آپ',
      'aiHistoryLoaded': 'چیٹ ہسٹری لوڈ ہوگئی',
      'aiTyping': 'اے آئی ٹائپ کر رہا ہے...',
      'skip': 'اسکپ',
      'next': 'اگلا',
      'getStarted': 'شروع کریں',
      'onboardingTitle1': 'موسم کے مطابق فصل کی منصوبہ بندی',
      'onboardingDesc1':
          'روزانہ موسم کی اپڈیٹس اور آسان زرعی رہنمائی حاصل کریں تاکہ بہتر فیصلے کیے جا سکیں۔',
      'onboardingTitle2': 'بہتر زرعی طریقے سیکھیں',
      'onboardingDesc2':
          'فصل کے مطابق معتبر ویڈیوز دیکھیں اور عملی مشوروں سے پیداوار بہتر بنائیں۔',
      'onboardingTitle3': 'اپنے کھیت کی نگرانی اعتماد سے کریں',
      'onboardingDesc3':
          'سینسر ٹرینڈز اور سفارشات سے آبپاشی اور مٹی کی دیکھ بھال بروقت پلان کریں۔',
    },
  };

  String t(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supportedLocale) => supportedLocale.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
