import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ur')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return localizations ?? AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'PakFasal',
      'welcome': 'Welcome to PakFasal',
      'login': 'Login',
      'signup': 'Sign Up',
      'or': 'OR',
      'email': 'Email',
      'username': 'Username',
      'usernameHint': 'John Doe',
      'emailHint': 'you@example.com',
      'password': 'Password',
      'passwordHint': '••••••••',
      'phone': 'Phone (Optional)',
      'phoneHint': '+92 300 0000000',
      'forgotPassword': 'Forgot Password?',
      'rememberMe': 'Remember Me',
      'requireBiometricAutofill': 'Require biometric unlock for autofill',
      'rememberMeHint':
          'Credentials are encrypted on this device. Biometric unlock may be required.',
      'resetPassword': 'Reset Password',
      'resetPasswordHint':
          'Enter your email address and we will send you a password reset link.',
      'sending': 'Sending...',
      'backToLogin': 'Back to Login',
      'home': 'Home',
      'learning': 'Learning',
      'weather': 'Weather',
      'askAi': 'Ask AI',
      'sensorData': 'Sensor Data',
      'marketplace': 'Marketplace',
      'cropCalendar': 'Crop Calendar',
      'offline': 'Offline',
      'online': 'Online',
      'cached': 'Cached',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'chat': 'Chat',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'saveChanges': 'Save Changes',
      'saving': 'Saving...',
      'profileUpdated': 'Profile updated successfully.',
      'voice': 'Voice',
      'notifications': 'Notifications',
      'quickAccess': 'Quick Access',
      'goodMorning': 'Good Morning!',
      'goodAfternoon': 'Good Afternoon!',
      'goodEvening': 'Good Evening!',
      'appTagline': 'Smart Farming, Better Tomorrow',
      'notificationIrrigationReminder':
          'Irrigation reminder: Check soil moisture today.',
      'notificationWeatherAlert':
          'Weather alert: Possible rain in next 24 hours.',
      'notificationMarketplaceOffer':
          'Marketplace: New fertilizer offer available.',
      'feelsLike': 'Feels like',
      'updatedJustNow': 'Updated just now',
      'wind': 'Wind',
      'latest': 'Latest',
      'dayShort': 'D',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'rainChance': 'Rain Chance',
      'weatherClear': 'Clear',
      'weatherCloudy': 'Cloudy',
      'weatherRain': 'Rain',
      'weatherSnow': 'Snow',
      'weatherStorm': 'Storm',
      'weatherGeneral': 'Weather',
      'soilMoisture': 'Soil Moisture',
      'phLevel': 'pH Level',
      'contact': 'Contact',
      'send': 'Send',
      'typeMessage': 'Type your question...',
      'listening': 'Listening...',
      'voiceInputUnavailable':
          'Voice input is unavailable. Please allow microphone permission.',
      'voicePermissionDenied':
          'Microphone permission is denied. Enable it from app settings.',
      'voiceServiceUnavailable':
          'Speech service is unavailable on this device. Please install/update Google Speech services.',
      'voiceInputStartFailed':
          'Could not start voice input. Please try again.',
      'voiceTapToSpeak': 'Tap mic to speak',
      'voiceListeningNow': 'Listening... speak now',
      'voiceProcessing': 'Processing voice input...',
      'openSettings': 'Open Settings',
      'good': 'Good',
      'moderate': 'Moderate',
      'bad': 'Bad',
      'errorState': 'Something went wrong.',
      'retry': 'Retry',
      'loading': 'Loading...',
      'learningSubtitle': 'Trusted farming videos by crop category',
      'featuredLearning': 'Featured Lesson',
      'watchNow': 'Watch Now',
      'learningEmpty': 'No videos found for this category yet.',
      'learningDemoMode':
          'Demo videos are shown. Add YOUTUBE_API_KEY using --dart-define to load live YouTube data.',
      'marketSearchHint': 'Search product name',
      'marketFilterCompany': 'Filter by company',
      'marketOfflineCached': 'Showing cached products while offline.',
      'marketNoProducts': 'No products match your search or filters.',
      'marketCompany': 'Company',
      'marketCategory': 'Category',
      'marketDetail': 'Product Detail',
      'marketLocation': 'Location',
      'callCompany': 'Call Company',
      'whatsapp': 'WhatsApp',
      'verified': 'Verified',
      'soilMoistureTrend': 'Soil Moisture Trend (7 days)',
      'phTrend': 'pH Trend (7 days)',
      'dssRecommendation': 'Smart Recommendation',
      'sensorRecommendationText':
          'Soil moisture is healthy. Keep next irrigation after 24-36 hours and apply balanced fertilizer this week.',
      'lastUpdated': 'Last updated',
      'sensorCloudLive': 'Live cloud sensor stream connected.',
      'sensorCloudError': 'Cloud unavailable. Showing cached/demo sensor data.',
      'sensorManualInputTitle': 'Manual Sensor Input',
      'sensorCropLabel': 'Crop',
      'sensorMoistureInput': 'Soil Moisture (%)',
      'sensorPhInput': 'Soil pH',
      'sensorRainExpected': 'Rain expected in next 24 hours',
      'sensorGenerateDss': 'Generate DSS Recommendation',
      'sensorSaveSession': 'Save Session',
      'sensorExportReadings': 'Export Readings',
      'sensorSessionSaved': 'Sensor session saved.',
      'sensorCopiedClipboard': 'Readings copied as CSV to clipboard.',
      'sensorRecIrrigateSoon': 'Irrigation needed within 12-24 hours',
      'sensorRecWaitRain':
          'Moisture is low but rain is expected, wait and recheck',
      'sensorRecReduceIrrigation':
          'Reduce irrigation frequency to avoid water logging',
      'sensorRecMoistureOk': 'Moisture is in acceptable range',
      'sensorRecAcidic': 'Soil is acidic, add lime and balanced fertilizer',
      'sensorRecAlkaline': 'Soil is alkaline, apply gypsum and organic matter',
      'sensorRecPhSuitable': 'pH is suitable for',
      'splashTagline': 'Smart farming for Pakistan',
      'authSubtitle': 'Sign in to continue',
      'continueAsGuest': 'Continue as Guest',
      'authSignOut': 'Sign out',
      'authLoggingIn': 'Signing in...',
      'authCreatingAccount': 'Creating account...',
      'emailRequired': 'Email is required',
      'usernameRequired': 'Username is required',
      'usernameMinLength': 'Username must be at least 3 characters',
      'passwordMin': 'Minimum 6 characters required',
      'weakPasswordForm': 'Password must be at least 6 characters',
      'invalidEmail': 'Enter a valid email address',
      'userDisabled': 'This account has been disabled.',
      'userNotFound': 'No account found for this email.',
      'wrongPassword': 'Incorrect password. Try again.',
      'emailInUse': 'This email is already registered.',
      'weakPasswordAuth': 'Password is too weak.',
      'tooManyRequests': 'Too many attempts. Try again later.',
      'networkFailed': 'Network error. Check your connection.',
      'authUnknown': 'Authentication failed. Please try again.',
      'resetEmailSent': 'Password reset link sent to your email.',
      'confirmPassword': 'Confirm password',
      'confirmPasswordRequired': 'Please confirm your password',
      'passwordsMismatch': 'Passwords do not match.',
      'invalidPhone': 'Enter a valid phone number',
      'selectCrop': 'Select Crop',
      'cropWheat': 'Wheat',
      'cropRice': 'Rice',
      'cropCotton': 'Cotton',
      'cropSugarcane': 'Sugarcane',
      'cropMaize': 'Maize',
      'couldNotOpenVideo': 'Could not open video link',
      'couldNotOpenDialer': 'Could not open dialer',
      'couldNotOpenWhatsapp': 'Could not open WhatsApp',
      'aiSampleQuestion': 'How to save wheat from pests?',
      'aiSampleAnswer':
          'Use approved pesticide early morning and monitor weekly.',
      'aiPendingResponse':
          'Thanks! AI response will be connected in backend integration.',
      'aiHistory': 'History',
      'aiNewChat': 'New chat',
      'aiNoMessagesTitle': 'Start your first AI chat',
      'aiNoMessagesSubtitle':
          'Ask about crops, pests, weather, or fertilizer recommendations.',
      'aiAssistantLabel': 'PakFasal AI',
      'aiYouLabel': 'You',
      'aiHistoryLoaded': 'Chat history loaded',
      'aiTyping': 'AI is typing...',
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'onboardingTitle1': 'Weather-smart crop planning',
      'onboardingDesc1':
          'Get daily weather updates and farm-friendly insights before every field decision.',
      'onboardingTitle2': 'Learn better farming practices',
      'onboardingDesc2':
          'Watch trusted lessons by crop type and improve yield with practical guidance.',
      'onboardingTitle3': 'Track your farm with confidence',
      'onboardingDesc3':
          'Use sensor trends and recommendations to plan irrigation and soil care on time.',
    },
    'ur': {
      'appName': 'پاک فصل',
      'welcome': 'پاک فصل میں خوش آمدید',
      'login': 'لاگ اِن',
      'signup': 'رجسٹر کریں',
      'or': 'یا',
      'email': 'ای میل',
      'username': 'صارف نام',
      'usernameHint': 'مثال: علی خان',
      'emailHint': 'you@example.com',
      'password': 'پاس ورڈ',
      'passwordHint': '••••••••',
      'phone': 'فون (اختیاری)',
      'phoneHint': '+92 300 0000000',
      'forgotPassword': 'پاس ورڈ بھول گئے؟',
      'rememberMe': 'مجھے یاد رکھیں',
      'requireBiometricAutofill': 'آٹو فل کے لیے بایومیٹرک تصدیق لازمی کریں',
      'rememberMeHint':
          'لاگ اِن معلومات اس ڈیوائس پر خفیہ انداز میں محفوظ ہوتی ہیں اور بایومیٹرک تصدیق درکار ہو سکتی ہے۔',
      'resetPassword': 'پاس ورڈ ری سیٹ کریں',
      'resetPasswordHint':
          'اپنا ای میل درج کریں، ہم آپ کو پاس ورڈ ری سیٹ لنک بھیجیں گے۔',
      'sending': 'بھیجا جا رہا ہے...',
      'backToLogin': 'لاگ اِن پر واپس جائیں',
      'home': 'ہوم',
      'learning': 'سیکھیں',
      'weather': 'موسم',
      'askAi': 'اے آئی سے پوچھیں',
      'sensorData': 'سینسر ڈیٹا',
      'marketplace': 'مارکیٹ پلیس',
      'cropCalendar': 'فصل کیلنڈر',
      'offline': 'آف لائن',
      'online': 'آن لائن',
      'cached': 'محفوظ',
      'lightMode': 'لائٹ موڈ',
      'darkMode': 'ڈارک موڈ',
      'language': 'زبان',
      'chat': 'چیٹ',
      'alerts': 'الرٹس',
      'profile': 'پروفائل',
      'saveChanges': 'تبدیلیاں محفوظ کریں',
      'saving': 'محفوظ کیا جا رہا ہے...',
      'profileUpdated': 'پروفائل کامیابی سے اپڈیٹ ہو گئی۔',
      'voice': 'آواز',
      'notifications': 'اطلاعات',
      'quickAccess': 'فوری رسائی',
      'goodMorning': 'صبح بخیر!',
      'goodAfternoon': 'دوپہر بخیر!',
      'goodEvening': 'شام بخیر!',
      'appTagline': 'اسمارٹ فارمنگ، بہتر کل',
      'notificationIrrigationReminder':
          'آبپاشی یاددہانی: آج مٹی کی نمی چیک کریں۔',
      'notificationWeatherAlert':
          'موسمی الرٹ: اگلے 24 گھنٹوں میں بارش کا امکان ہے۔',
      'notificationMarketplaceOffer':
          'مارکیٹ پلیس: کھاد کی نئی پیشکش دستیاب ہے۔',
      'feelsLike': 'محسوس ہوتا ہے',
      'updatedJustNow': 'ابھی اپڈیٹ ہوا',
      'wind': 'ہوا',
      'latest': 'تازہ ترین',
      'dayShort': 'دن',
      'temperature': 'درجہ حرارت',
      'humidity': 'نمی',
      'rainChance': 'بارش کا امکان',
      'weatherClear': 'صاف موسم',
      'weatherCloudy': 'ابر آلود',
      'weatherRain': 'بارش',
      'weatherSnow': 'برف',
      'weatherStorm': 'طوفانی',
      'weatherGeneral': 'موسم',
      'soilMoisture': 'مٹی کی نمی',
      'phLevel': 'پی ایچ لیول',
      'contact': 'رابطہ',
      'send': 'بھیجیں',
      'typeMessage': 'اپنا سوال لکھیں...',
      'listening': 'سن رہا ہے...',
      'voiceInputUnavailable':
          'آواز سے لکھنے کی سہولت دستیاب نہیں۔ براہ کرم مائیکروفون کی اجازت دیں۔',
      'voicePermissionDenied':
          'مائیکروفون کی اجازت نہیں دی گئی۔ براہ کرم ایپ سیٹنگز سے اجازت دیں۔',
      'voiceServiceUnavailable':
          'اس ڈیوائس پر اسپیچ سروس دستیاب نہیں۔ براہ کرم گوگل اسپیچ سروس اپڈیٹ/انسٹال کریں۔',
      'voiceInputStartFailed':
          'وائس ان پٹ شروع نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
      'voiceTapToSpeak': 'بولنے کے لیے مائیک دبائیں',
      'voiceListeningNow': 'سن رہا ہے... اب بولیں',
      'voiceProcessing': 'آواز کو متن میں بدلا جا رہا ہے...',
      'openSettings': 'سیٹنگز کھولیں',
      'good': 'اچھا',
      'moderate': 'درمیانہ',
      'bad': 'خراب',
      'errorState': 'کچھ غلط ہوگیا۔',
      'retry': 'دوبارہ کوشش',
      'loading': 'لوڈ ہو رہا ہے...',
      'learningSubtitle': 'فصل کے حساب سے قابل اعتماد زرعی ویڈیوز',
      'featuredLearning': 'نمایاں سبق',
      'watchNow': 'ابھی دیکھیں',
      'learningEmpty': 'اس کیٹیگری کے لیے ابھی ویڈیوز دستیاب نہیں۔',
      'learningDemoMode':
          'ڈیمو ویڈیوز دکھائی جا رہی ہیں۔ لائیو یوٹیوب ڈیٹا کے لیے --dart-define کے ساتھ YOUTUBE_API_KEY شامل کریں۔',
      'marketSearchHint': 'پروڈکٹ کا نام تلاش کریں',
      'marketFilterCompany': 'کمپنی کے مطابق فلٹر',
      'marketOfflineCached':
          'آف لائن حالت میں محفوظ شدہ پروڈکٹس دکھائی جا رہی ہیں۔',
      'marketNoProducts': 'تلاش یا فلٹر کے مطابق کوئی پروڈکٹ نہیں ملی۔',
      'marketCompany': 'کمپنی',
      'marketCategory': 'قسم',
      'marketDetail': 'پروڈکٹ کی تفصیل',
      'marketLocation': 'مقام',
      'callCompany': 'کمپنی کو کال کریں',
      'whatsapp': 'واٹس ایپ',
      'verified': 'تصدیق شدہ',
      'soilMoistureTrend': 'مٹی کی نمی کا رجحان (7 دن)',
      'phTrend': 'پی ایچ رجحان (7 دن)',
      'dssRecommendation': 'سمارٹ سفارش',
      'sensorRecommendationText':
          'مٹی کی نمی مناسب ہے۔ اگلی آبپاشی 24 سے 36 گھنٹے بعد کریں اور اس ہفتے متوازن کھاد استعمال کریں۔',
      'lastUpdated': 'آخری اپ ڈیٹ',
      'sensorCloudLive': 'لائیو کلاؤڈ سینسر ڈیٹا منسلک ہے۔',
      'sensorCloudError':
          'کلاؤڈ دستیاب نہیں۔ محفوظ/ڈیمو سینسر ڈیٹا دکھایا جا رہا ہے۔',
      'sensorManualInputTitle': 'دستی سینسر ان پٹ',
      'sensorCropLabel': 'فصل',
      'sensorMoistureInput': 'مٹی کی نمی (%)',
      'sensorPhInput': 'مٹی کا پی ایچ',
      'sensorRainExpected': 'اگلے 24 گھنٹوں میں بارش متوقع ہے',
      'sensorGenerateDss': 'ڈی ایس ایس سفارش بنائیں',
      'sensorSaveSession': 'سیشن محفوظ کریں',
      'sensorExportReadings': 'ریڈنگز ایکسپورٹ کریں',
      'sensorSessionSaved': 'سینسر سیشن محفوظ ہوگیا۔',
      'sensorCopiedClipboard': 'ریڈنگز CSV فارمیٹ میں کلپ بورڈ پر کاپی ہوگئیں۔',
      'sensorRecIrrigateSoon': 'اگلے 12-24 گھنٹوں میں آبپاشی کریں',
      'sensorRecWaitRain':
          'نمی کم ہے مگر بارش متوقع ہے، انتظار کریں اور دوبارہ چیک کریں',
      'sensorRecReduceIrrigation':
          'پانی کھڑا ہونے سے بچنے کے لیے آبپاشی کی مقدار کم کریں',
      'sensorRecMoistureOk': 'نمی مناسب حد میں ہے',
      'sensorRecAcidic': 'مٹی تیزابی ہے، چونا اور متوازن کھاد استعمال کریں',
      'sensorRecAlkaline': 'مٹی الکلائن ہے، جپسم اور نامیاتی مادہ استعمال کریں',
      'sensorRecPhSuitable': 'پی ایچ موزوں ہے برائے',
      'splashTagline': 'پاکستان کے لیے ذہین کھیت باڑی',
      'authSubtitle': 'جاری رکھنے کے لیے لاگ اِن کریں',
      'continueAsGuest': 'مہمان کے طور پر جاری رکھیں',
      'authSignOut': 'لاگ آؤٹ',
      'authLoggingIn': 'لاگ اِن ہو رہا ہے...',
      'authCreatingAccount': 'اکاؤنٹ بنایا جا رہا ہے...',
      'emailRequired': 'ای میل درکار ہے',
      'usernameRequired': 'صارف نام درکار ہے',
      'usernameMinLength': 'صارف نام کم از کم 3 حروف کا ہونا چاہیے',
      'passwordMin': 'کم از کم 6 حروف درکار ہیں',
      'weakPasswordForm': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
      'invalidEmail': 'درست ای میل درج کریں',
      'userDisabled': 'یہ اکاؤنٹ غیر فعال کردیا گیا ہے۔',
      'userNotFound': 'اس ای میل پر کوئی اکاؤنٹ نہیں ملا۔',
      'wrongPassword': 'غلط پاس ورڈ۔ دوبارہ کوشش کریں۔',
      'emailInUse': 'یہ ای میل پہلے سے رجسٹرڈ ہے۔',
      'weakPasswordAuth': 'پاس ورڈ بہت کمزور ہے۔',
      'tooManyRequests': 'بہت زیادہ کوششیں۔ بعد میں کوشش کریں۔',
      'networkFailed': 'نیٹ ورک خرابی۔ کنکشن چیک کریں۔',
      'authUnknown': 'لاگ اِن ناکام۔ دوبارہ کوشش کریں۔',
      'resetEmailSent': 'پاس ورڈ ری سیٹ کا لنک آپ کی ای میل پر بھیج دیا گیا۔',
      'confirmPassword': 'پاس ورڈ دوبارہ',
      'confirmPasswordRequired': 'براہ کرم پاس ورڈ دوبارہ درج کریں',
      'passwordsMismatch': 'پاس ورڈ میل نہیں کھاتے۔',
      'invalidPhone': 'درست فون نمبر درج کریں',
      'selectCrop': 'فصل منتخب کریں',
      'cropWheat': 'گندم',
      'cropRice': 'چاول',
      'cropCotton': 'کپاس',
      'cropSugarcane': 'گنا',
      'cropMaize': 'مکئی',
      'couldNotOpenVideo': 'ویڈیو لنک نہیں کھل سکا',
      'couldNotOpenDialer': 'ڈائلر نہیں کھل سکا',
      'couldNotOpenWhatsapp': 'واٹس ایپ نہیں کھل سکا',
      'aiSampleQuestion': 'گندم کو کیڑوں سے کیسے بچاؤں؟',
      'aiSampleAnswer':
          'منظور شدہ اسپرے صبح سویرے کریں اور ہفتہ وار نگرانی کریں۔',
      'aiPendingResponse':
          'شکریہ! اے آئی جواب بیک اینڈ انٹیگریشن کے بعد دستیاب ہوگا۔',
      'aiHistory': 'ہسٹری',
      'aiNewChat': 'نئی چیٹ',
      'aiNoMessagesTitle': 'اپنی پہلی اے آئی چیٹ شروع کریں',
      'aiNoMessagesSubtitle':
          'فصل، کیڑے، موسم یا کھاد کے بارے میں سوال پوچھیں۔',
      'aiAssistantLabel': 'پاک فصل اے آئی',
      'aiYouLabel': 'آپ',
      'aiHistoryLoaded': 'چیٹ ہسٹری لوڈ ہوگئی',
      'aiTyping': 'اے آئی ٹائپ کر رہا ہے...',
      'skip': 'اسکپ',
      'next': 'اگلا',
      'getStarted': 'شروع کریں',
      'onboardingTitle1': 'موسم کے مطابق فصل کی منصوبہ بندی',
      'onboardingDesc1':
          'روزانہ موسم کی اپڈیٹس اور آسان زرعی رہنمائی حاصل کریں تاکہ بہتر فیصلے کیے جا سکیں۔',
      'onboardingTitle2': 'بہتر زرعی طریقے سیکھیں',
      'onboardingDesc2':
          'فصل کے مطابق معتبر ویڈیوز دیکھیں اور عملی مشوروں سے پیداوار بہتر بنائیں۔',
      'onboardingTitle3': 'اپنے کھیت کی نگرانی اعتماد سے کریں',
      'onboardingDesc3':
          'سینسر ٹرینڈز اور سفارشات سے آبپاشی اور مٹی کی دیکھ بھال بروقت پلان کریں۔',
    },
  };

  String t(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supportedLocale) => supportedLocale.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
