// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcvAN5pCLfXDri31BzRy_05m2WrWTFvw',
    appId: '1:669661525637:web:4e0504ff1f1455be0f1bec',
    messagingSenderId: '669661525637',
    projectId: 'pakfasalapp',
    authDomain: 'pakfasalapp.firebaseapp.com',
    storageBucket: 'pakfasalapp.firebasestorage.app',
    measurementId: 'G-VB217VDXWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ_nJ5l2Rak_aAd7inOJJpqOqNzwz4UN0',
    appId: '1:669661525637:android:0d3cf53360771c130f1bec',
    messagingSenderId: '669661525637',
    projectId: 'pakfasalapp',
    storageBucket: 'pakfasalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlsr1_Zc82HzW6NX4-cdnZHsyqXR4GKEc',
    appId: '1:669661525637:ios:8e7250c0bdc776a10f1bec',
    messagingSenderId: '669661525637',
    projectId: 'pakfasalapp',
    storageBucket: 'pakfasalapp.firebasestorage.app',
    iosBundleId: 'com.example.pakfasalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlsr1_Zc82HzW6NX4-cdnZHsyqXR4GKEc',
    appId: '1:669661525637:ios:8e7250c0bdc776a10f1bec',
    messagingSenderId: '669661525637',
    projectId: 'pakfasalapp',
    storageBucket: 'pakfasalapp.firebasestorage.app',
    iosBundleId: 'com.example.pakfasalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFcvAN5pCLfXDri31BzRy_05m2WrWTFvw',
    appId: '1:669661525637:web:9b0fe7ae48c172150f1bec',
    messagingSenderId: '669661525637',
    projectId: 'pakfasalapp',
    authDomain: 'pakfasalapp.firebaseapp.com',
    storageBucket: 'pakfasalapp.firebasestorage.app',
    measurementId: 'G-VGP1GWNTP5',
  );
}
